name: Download Maven Dependencies

on:
  push:

jobs:
  mvn_deps:
    name: Download Maven Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Checkout repository maven-depmgt-pom
        uses: actions/checkout@v3
        with:
          ref: develop
          repository: Meeds-io/maven-depmgt-pom
      - name: Run mvn go-offline
        run: mvn -B dependency:go-offline --fail-never -Dmaven.artifact.threads=300
      - name: Archiving m2 local repository
        run: cd ~/.m2 && tar --zstd -cvf m2.tar.zst repository && md5sum m2.tar.zst > m2.tar.zst.md5
      - name: Upload to storage
        run: cd ~/.m2 && curl -T m2.tar.zst ${{ secrets.MVN_STORAGE_URL }} && curl -T m2.tar.zst.md5 ${{ secrets.MVN_STORAGE_URL }}