name: Create Git Feature Branches for PLF projects 

on:
  workflow_dispatch:
    inputs:
      ORIGIN_BRANCH: 
        type: text
        description: like develop-meed or develop or develop-exo 
      ISSUE: 
        type: text
        description: the task id 'task-1234'      
      BRANCH:
        type: text
        description: the feature branche you want to add it like mips devx ...
      VALIDATE:
        type: boolean
        description: 'Whether to validate the changes before pushing to the branch'
        default: false

jobs:
  create_fb:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
       - name: Checkout
         uses: actions/checkout@v3
         with: 
           ref: habib
           token: ${{ secrets.SWF_TOKEN }}
       - name: install ssh
         uses: shimataro/ssh-key-action@v2
         with:
           key: ${{ secrets.SSH_KEY }}
           known_hosts: ${{ secrets.KNOWN_HOSTS }}.
      #  - name: Set Git user email and name
      #    env:
      #      GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
      #      GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
      #    run: |
      #      git config --global user.email "$GIT_USER_EMAIL"
      #      git config --global user.name "$GIT_USER_NAME"
       - name: run createFB script
         env:
          ORIGIN_BRANCH: ${{ github.event.inputs.ORIGIN_BRANCH }}
          BRANCH: ${{ github.event.inputs.BRANCH }}
          ISSUE: ${{ github.event.inputs.ISSUE }}
         run: |
            cd git-workflow
            if [[ ${{inputs.VALIDATE}} == 'false' ]]; then
              PUSH=false
            else
              PUSH=true
            fi
            ./createFB.sh $BRANCH $ORIGIN_BRANCH $ISSUE $PUSH
         shell: bash