name: Create Git Feature Branches for PLF projects 

on:
  workflow_dispatch:
    inputs:
      ORIGIN_BRANCH: 
        type: text
        description: like develop-meed or develop or develop-exo 
      ISSUE: 
        type: text
        description: the task id 'task-1234'      
      BRANCH:
        type: text
        description: the feature branche you want to add it like mips devx ...
# concurrency:
#   group: once-per-time

jobs:
  create_fb:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
       - name: Checkout
         uses: actions/checkout@v3
         with: 
           ref: master
           token: ${{ secrets.SWF_TOKEN }}
       - name: install ssh
         uses: shimataro/ssh-key-action@v2
         with:
           key: ${{ secrets.SSH_KEY }}
           known_hosts: ${{ secrets.KNOWN_HOSTS }}.
       - name: run createFB script
         env:
          ORIGIN_BRANCH: ${{ github.event.inputs.ORIGIN_BRANCH }}
          BRANCH: ${{ github.event.inputs.BRANCH }}
          ISSUE: ${{ github.event.inputs.ISSUE }}
         run: |
            cd git-workflow
            chmod +x createFB.sh 
            ./createFB.sh $BRANCH $ORIGIN_BRANCH $ISSUE
         shell: bash