name: Create Git Feature Branches for PLF projects 

on:
  workflow_dispatch:
    inputs:
      ORIGIN_BRANCH: 
        type: text
        description: like develop-meed or develop or develop-exo 
      TARGET_BRANCH:
        type: text
        description: the feature branche you want to add it like feature/$BRANCH
# concurrency:
#   group: once-per-time

jobs:
  create_fb:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
       - name: Checkout
         uses: actions/checkout@v3
         with: 
           ref: master
           token: ${{ secrets.SWF_TOKEN }}
       - name: install ssh
         uses: shimataro/ssh-key-action@v2
         with:
           key: ${{ secrets.SSH_KEY }}
           known_hosts: ${{ secrets.KNOWN_HOSTS }}.
          #  config: |
          #    Host ${{ secrets.HOST }}
          #    HostName ${{ secrets.HOST }}
          #    User ${{ secrets.USERNAME }}
      #  - name: default meeds branch
       - name: run createFB script
         run: |
            chmod +x ../../git-workflow/createFB.sh
            ./git-workflow/createFB.sh
         shell: bash