name: PLF PR Task Webhook

on:
  workflow_call:
    inputs:
      TARGET_SERVER:
        description: Target Server (tribe or builders)
        default: 'tribe'
        required: false
        type: string
    secrets:
      SERVER_USERNAME:
        required: true
      SERVER_PASSWORD:
        required: true
      SERVER_TASK_REST_PREFIXE_URL:
        required: false
      SERVER_GAMGH_CONNECTOR_REST_URL:
        required: false
permissions:
  pull-requests: write
        
jobs:
  check_tasks:
    name: Check for tasks identifiers
    runs-on: ubuntu-latest
    steps:
      - name: Fetch eXo Server
        id: fetch
        run: |
          case ${{ inputs.TARGET_SERVER }} in
            tribe)
              echo regexFilter='(task|maint|exo)((-|_)[0-9]{4,})+' >> $GITHUB_OUTPUT
              echo portalSite='dw' >> $GITHUB_OUTPUT
              echo serverURL='https://community.exoplatform.com' >> $GITHUB_OUTPUT
              ;;

            builders)
              echo regexFilter='meed((-|_)[0-9]{2,})+' >> $GITHUB_OUTPUT
              echo portalSite='meeds' >> $GITHUB_OUTPUT
              echo serverURL='https://builders.meeds.io' >> $GITHUB_OUTPUT
              ;;

            *)
              echo "Error target Server ${{ inputs.TARGET_SERVER }} is not yet supported!"
              exit 1
            ;;
          esac 
      - name: PLF Tasks Webhook
        uses: hbenali/notifs-task@v1.0
        with:
          SERVER_URL: ${{ steps.fetch.outputs.serverURL }}
          SERVER_DEFAULT_SITENAME: ${{ steps.fetch.outputs.portalSite }}
          SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
          TASKS_REGEX_FILTER: "${{ steps.fetch.outputs.regexFilter }}"
          
  assign-author:
    name: Assign Pull Request Author
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'opened' }}
    steps:
      - uses: toshimaru/auto-author-assign@v1.6.1         